### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by connecteev** [muhamed-didovic/ccdown#1]
Encounter this error when I run `npm i -g ccdown`

```
npm i -g ccdown
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated har-validator@5.0.3: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.87.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /opt/homebrew/lib/node_modules/ccdown/node_modules/ytdl-run
npm ERR! command failed
npm ERR! command sh -c node ./install.js
npm ERR! installing youtube-dl...
npm ERR! /opt/homebrew/lib/node_modules/ccdown/node_modules/execa/index.js:174
npm ERR! 		err = new Error(`Command failed: ${joinedCmd}${output}`);
npm ERR! 		      ^
npm ERR!
npm ERR! Error: Command failed: /opt/homebrew/lib/node_modules/ccdown/node_modules/ytdl-run/bin/youtube-dl --version
npm ERR! env: python: No such file or directory
npm ERR!
npm ERR!
npm ERR!     at makeError (/opt/homebrew/lib/node_modules/ccdown/node_modules/execa/index.js:174:9)
npm ERR!     at /opt/homebrew/lib/node_modules/ccdown/node_modules/execa/index.js:278:16
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at async /opt/homebrew/lib/node_modules/ccdown/node_modules/ytdl-run/install.js:14:31 {
npm ERR!   code: 127,
npm ERR!   stdout: '',
npm ERR!   stderr: 'env: python: No such file or directory\n',
npm ERR!   failed: true,
npm ERR!   signal: null,
npm ERR!   cmd: '/opt/homebrew/lib/node_modules/ccdown/node_modules/ytdl-run/bin/youtube-dl --version',
npm ERR!   timedOut: false,
npm ERR!   killed: false
npm ERR! }
npm ERR!
npm ERR! Node.js v20.3.0
```

The `python` command (aliased to `python3`) is recognized by my terminal.

<img width="802" alt="image" src="https://github.com/muhamed-didovic/ccdown/assets/64816/8c977b6e-868c-4204-979e-43607a01fdc0">

Also, I have added /opt/homebrew/bin/python3 to my $PATH, but am still seeing this error.

**Comment by muhamed-didovic** [comment]
Hey, try to install yt-dlp manually

**Comment by connecteev** [comment]
I was able to install yt-dlp manually, and it looks like the terminal recognizes the command.
<img width="576" alt="image" src="https://github.com/muhamed-didovic/ccdown/assets/64816/a600a0d4-50c8-4696-97ab-8f901d953fb6">

Following that, I tried the installation steps of this repo again and see the same error when I run npm i -g ccdown
<img width="1427" alt="image" src="https://github.com/muhamed-didovic/ccdown/assets/64816/d9303c2f-a88a-42be-9dae-c158c4727138">

**Comment by muhamed-didovic** [comment]
Try to run with npx

**Comment by connecteev** [comment]
Thanks for helping resolve this problem, it sure is confounding. 

When I run this command with npx:
`npx ccdown -a -e 'valid_email@gmail.com -p 'valid_password' -d /Code/downloads/`

This is what I see in the output:
<img width="1425" alt="image" src="https://github.com/muhamed-didovic/ccdown/assets/64816/548654b7-01fd-48e0-bac1-74c97731ea84">

I don't think the command runs, because it returns almost immediately and nothing gets downloaded. The codecourse email and password are valid.

**Comment by connecteev** [comment]
Finally. I got the npm installation to work by following these instructions: https://stackoverflow.com/a/73298283

Specifically these commands helped:
```
sudo rm -rf /usr/local/bin/python
sudo ln -s $(which python3) /usr/local/bin/python
sudo chmod -R 777 /opt/homebrew/bin/ccdown
```
