### ISSUE TITLE
TypeError in cli.js: expecting an array or an iterable object but got [object Null]

### ISSUE THREAD

**Issue by aynaitlamine** [muhamed-didovic/ccdown#11]
I encountered an error while using the ccdown tool. After logging in and detecting courses, the following error occurs:

`
✔ Login...  completed.
  ✓ Found: 1 courses
MAIN errorr in cli.js: TypeError: expecting an array or an iterable object but got [object Null]
    at process.processImmediate (node:internal/timers:476:21)`

Steps to Reproduce:

1. Run the ccdown tool.
2. Complete the login process.
3. The tool finds the courses.
4. The error appears immediately after finding the courses.

Expected Behavior:
The tool should process the found courses without throwing a TypeError.

Actual Behavior:
A TypeError is thrown, indicating that an array or iterable object was expected but a null object was received.

**Comment by muhamed-didovic** [comment]
hey @aynaitlamine, Alex changed the design and layout... I'll update scraper

**Comment by muhamed-didovic** [comment]
hey @aynaitlamine, pushed new version, please update it and let me know how it goes

**Comment by aynaitlamine** [comment]
Hi @muhamed-didovic ,

Thank you for the quick response. I have tested it and it works perfectly.
 I am closing this issue as completed.
