### ISSUE TITLE
Downloading all courses that belong to a subject?

### ISSUE THREAD

**Issue by connecteev** [muhamed-didovic/ccdown#4]
Is there a way to download all courses that belong to a subject? For example: all courses within:

1. https://codecourse.com/subjects/flutter/index
2. https://codecourse.com/subjects/vue-js/index
3. https://codecourse.com/subjects/laravel/index

Could this be an easy addition? Thanks!

**Comment by muhamed-didovic** [comment]
I could add this when other things are implemented :)

**Comment by connecteev** [comment]
This is one option / approach :)

The other better approach / workflow (infinitely flexible) is what I described here: https://github.com/muhamed-didovic/ccdown/issues/3#issuecomment-1602608106

This could be a nice addition after that workflow is implemented!

**Comment by connecteev** [comment]
Implemented in ccdown v 0.20.1, per https://github.com/muhamed-didovic/ccdown/issues/3#issuecomment-1607626137

To download all courses that belong to a subject:
✔ Do you want all courses? … no
✔ Choose "Y" if you want to search for a course otherwise choose "N" if you have a link for download … no
✔ Enter url for download. … https://codecourse.com/subjects/flutter

Thanks @muhamed-didovic!
