### ISSUE TITLE
Also download source code (if available as a downloadable file) when downloading a course 

### ISSUE THREAD

**Issue by connecteev** [muhamed-didovic/ccdown#5]
When downloading a course, also download source code (if available as a downloadable file) into the same target folder for videos.

There are 3 types of courses (listed below). Can I suggest that we download the source code for type 2 (with source code available as a downloadable file)?

1. Some courses don't have any links to source code (example: https://codecourse.com/watch/standardised-responses-with-laravel-responsables?part=standardised-responses-with-laravel-responsables)

2. Some courses have a button at the bottom of every video, that says "[Download full source code](https://codecourse.com/files/345/download)". Example:
https://codecourse.com/watch/custom-user-subdomains-in-laravel?part=introduction-and-demo-custom-user-subdomains-laravel

3. Other courses have a button that says [Full source on GitHub](https://github.com/codecourse/laravel-passwordless-authentication). Example:
https://codecourse.com/watch/passwordless-authentication-with-laravel-2023?part=introduction-and-demo-paswordless-authentication-2023

**Comment by muhamed-didovic** [comment]
I forgot last night to push a new change regarding the source, so there is now Github link in markdown file for the source if it is available, I'll see to update code so we have source code as well, but before that, I'll need to make some general changes for logging and etc like you already noticed...

Also regarding 2. point it is the same source code for all videos

**Comment by connecteev** [comment]
Awesome, look forward to it! 

Idea for this issue:
For courses of type 2, it could download the source code file into the same folder as the videos.
For courses of type 3 (link to public github), it could create a text file (code.txt) with a link to the public github....and put that file in the same folder as the videos.

This would work great with the workflow I described here
https://github.com/muhamed-didovic/ccdown/issues/3#issuecomment-1602608106

**Comment by connecteev** [comment]
@muhamed-didovic would it be possible to get this out next, regardless of which option you pick:

1. single course download
2. multiple course download (multiple selection)
3. multiple course download from a file
4. download all courses in a subject
5. download all courses

In all cases, the source code (if the button to download the source files is available) should also be downloaded / included. Doing this would be a huge time saver.

**Comment by muhamed-didovic** [comment]
hey @connecteev, before I add that feature, I was wondering what you intent to do with all the videos and source code as well?

**Comment by connecteev** [comment]
@muhamed-didovic this is for my offline consumption and learning only. Not going to share any of the videos or source code with non-members, if that's your question.

**Comment by connecteev** [comment]
I also left a note on #8, It would be good to provide this option. thanks for considering. 

ccdown
✔ Do you want all courses? … no
✔ Choose "Y" if you want to search for a course otherwise choose "N" if you have a link for download … no
✔ Enter url for download. … https://codecourse.com/subjects/laravel-livewire
✔ Choose "Y" if you want to include the source code (if available), choose "N" if you don't want to include source code, choose 'C' if you ONLY want to download the source code ... code

Typing 'C' could autocomplete to 'code' and only download the source code for each course on the selection list. The folder structure sould be the same, and contain the source code files, like this:
* 238-Build a Podcast App/podcast.zip
* 256-Build a Distraction Dashboard/ distract.zip
* and so on

**Comment by connecteev** [comment]
@muhamed-didovic Any chance you can take a look at this?
